server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/book_social_network
    username: bsn_dev
    password: bsnDev@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: bsnmail
    password: bsnmail123
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        timeout: 3000
        writetimeout: 5000
        connectiontimeout: 5000

application:
  security:
    jwt:
      secretKey: Tk5kiAvKMwgLe5ICJiuiKu8Up2JEgiyM
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account